#!/usr/bin/bash
: "${HOOK_URL:?}"

tmp_result=$(mktemp -t website-monitor.XXXXXX) && cp ./monitor-db "$tmp_result"
while IFS=' ' read -r url name last_status _; do 
  time=$(curl -LIsf --retry 2 --max-time 15 "$url" -w '%{time_total}' -o /dev/null)
  case $? in 
    0) (( $(echo "$time <= 5" | bc -l ) )) && status="UP" || status="SLOW" ;;
    22|28) status="DOWN" ;;
    *) continue ;;
  esac
  echo "Exit code for $name ($url): $?, time taken: $time"

  [[ $status == "$last_status" ]] && continue
  echo "$name changed to $status"

  case $status in 
    'UP') message="{\"content\": \"✅ **$name** está online!\"}" ;; 
    'DOWN') message="{\"content\": \"❌ **$name** está fora do ar! 😞\"}" ;;
    'SLOW') message="{\"content\": \"⌛ **$name** está apresentando lentidão!\"}" ;;
  esac
  curl -H "Content-Type: application/json" -X POST -d "$message" "$HOOK_URL"
  sed -i "s|$url $name $last_status .*|$url $name $status $(date -Is)|" "$tmp_result"
done < ./monitor-db
mv "$tmp_result" ./monitor-db
