#!/usr/bin/bash
: "${WEBSITE_DB:=./monitor-db}" 
: "${HOOK_URL:?}"

tmp_result=$(mktemp website-monitor.XXXXXX)
while IFS=' ' read -r url name last_status _; do 
  curl -LIsf --retry 2 --max-time 10 "$url" > /dev/null
  echo "cUrl exit code for $name ($url): $?"
  case $? in 
    0) status="UP" ;;
    22|28) status="DOWN" ;;
    *) continue ;;
  esac

  if [[ $status != "$last_status" ]]; then
    echo "$name changed to $status"
    message=$([[ $status == UP ]] && echo "✅ **$name** está online!" || echo "❌ **$name** caiu!")
    curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$message\"}" "$HOOK_URL"
  fi
  echo "$url $name $status $(date -Is)" >> "$tmp_result"
done < "$WEBSITE_DB"
mv "$tmp_result" "$WEBSITE_DB"
