#!/usr/bin/bash
: "${WEBSITE_DB:=./monitor-db}" && [[ -f $WEBSITE_DB ]] || { echo "Missing website database: $WEBSITE_DB"; exit 1; }
: "${HOOK_URL:?}"
ping -c 1 8.8.8.8 &>/dev/null ||  { echo "Network is down, skipping website checks."; exit 1; }

while IFS=' ' read -r url name last_status _; do 
  status_code=$(curl -Is --retry 2 --max-time 20 -L -w "%{http_code}" -o /dev/null "$url")
  case $? in
    0) echo "Response for $name ($url): $status_code"; [[ $status_code == 200 ]] && status="UP" || status="DOWN" ;;
    28) echo "Timeout while checking $name ($url)"; status="DOWN" ;;
    *) echo "Curl error $? while checking $name ($url), leaving unchanged" ; continue ;;
  esac

  if [[ $status != $last_status ]]; then 
    message=$([[ $status == UP ]] && echo "✅ **$name** está online!" || echo "❌ **$name** caiu!")
    curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$message\"}" "$HOOK_URL"
    sed -i "s#^$url $name $last_status .*#$url $name $status $(date -Is)#" "$WEBSITE_DB"
    echo "$name changed to $status"
  fi
done < "$WEBSITE_DB"
